This is the begining-of-the-user-manual

== Overview
Fineract is a headless core banking platform meaning it does not have a UI(the Mifos UI generally works with Fineract but may not fully support all apache fineract features). It is fully API driven whereby all operations are carried out by making API calls and getting a response.

The platform supports most of the standard banking operations: client management, account management, loans, accounting, short/long term deposits and reporting.

A number of configurative and administrative features are available out of the box, these include: roles and permissions, product definition, user management, maker/checker, two factor authentication and many more.

As an open-source project, Fineract is constantly being updated with new features and improvements.


== Why Fineract
Fineract is a feature rich open source core banking platform and compares well with other core banking systems. The major advantages of using fineract are:

* Open source with an active community of contributors who are passionate about providing world class banking system
* No vendor lock-in, there is a wide range of implementors available to support with implementation, enhancement and post go live support
* Fully API driven allowing building of applications on top of it and super easy to integrate third party services

== Quick install and run Fineract
Fineract is a Springboot application and can be deployed like any other such app. To get the platform up and running fast, follow these steps:
* one
* two
* three

Other methods of deploying fineract for various use cases can be found here(a page with methods to deploy fineract in enterprise ready scenarions with scalability, resilience, etc) 

== Prerequisite configurations
Before using fineract, a number of configurations have to be completed. These include:

=== Offices
Use this feature to setup the organization office hierarchy that represents the physical office structure. By default, the head office will be available. The platform supports children of children hierarchy, for example: Head office/Regional office/Sub region office/Office/Field office

Customers and users must be tagged to an office. 

User access can be limited to an office with the user having access to the office they have been tagged to and all offices below.

For digital banks, the head office should suffice.

=== Currency
Use this feature to add currenc(ies). All products and fees require a currency to be tagged as the operating currency. Please note, each product/charge only supports one currency.

The platform does not support forex operations. Currency conversions have to be handled externally.

=== Employees 
Empployees are optionally tagged to customers, loans, savings and deposit accounts . They are also tagged(mandantory) in the teller module.

=== Payment types
Payment types are used to track the channel through which a payment was made. It can be useful for reconciliation and auditing purposes.

When used with accounting module, the payment type is linked to a GL account and determines the account debited or credited when the payment type is used in a transaction.

=== Roles and permissions
Fineract supports fine grained permission setup with each activity requiring a permission to execute.

Users are assigned role(s). Permissions are granted to roles.

=== System users
This feature allows creation and management(change password,edit and delete) of system users.

User passwords can be entered by the system admin manually or auto-generated by the system at account creation and sent to user email address.

Note: Fineract supports integration with Identity and Access Management platforms like Keycloak where user account details are stored and managed.

=== Manage codes
Fields that require options such as client gender, address type and so on are created and maintained using the manage codes feature.

This is especially useful when building a graphical user interface. Most of the drop down fields options will be defined and managed here.

== Products configuration
Products are templates used to define the expected behavior of a saving,deposit,loan accounts and fees. For example, the minimum and maximum loan term. 

=== Loans
Loan product configuration has a lot of options that allow the platform to cater for a wide range of use cases. These configurations can be combined to meet the most common scenarios and some unique ones.

* Amortization: 
** Equal installments 
** Equal principal installment
* Interest method: 
** Flat 
** Declining balance
* Repayment strategy(this determines distribution priority of amount repaid)
- Penalties, Fees, Interest, Principal order
- Overdue/Due Fee/Int,Principal
- Principal, Interest, Penalties, Fees Order
- Interest, Principal, Penalties, Fees Order
- Early Repayment Strategy
- HeavensFamily Unique
- Creocore Unique
* Floating(variable) interest or fixed
* Repayment periods
- Weekly
- Monthly
- Daily
* Moratorium on principal/interest or both
* Interest free period
* Arrears tolerance
* Days in a year can be set as [360,364,365 or actual]
* Tracking non perfoming loans
* Loan top up(refinance)
* Interest recalculation
* Loan guarantee using customer savings
* Multiple disbursement(tranche) loans
* Overdue penalty charge
* Accounting integration with cash based, periodic accrual and upfront accrual support

=== Fixed deposits
=== Savings
=== Recurring deposits
=== Fees and charges
== Accounting
=== Chart of accounts
=== Search journal entries
=== Journal entries
=== Frequent postings
== Clients management
== Group management
== Accounts management
=== Open account
=== Deposit
=== Withdraw
== Loan management
=== Application
=== Approval
=== Disbursement
== Workflow management
== Reporting
=== Table reports
=== Pentaho reports
== Data import
=== Deposits

The section <<_accounting>> is the entry point to this user manual

<<link-macro-attributes , begining of the user manual>>

Learn how to <<link-macro-attributes,use attributes within the link macro>>.